[["file:///var/www/html/designpattern1/coreconcept/vendor/mindplay/annotations/test/lib/xTestException.php",{"_uri":"file:///var/www/html/designpattern1/coreconcept/vendor/mindplay/annotations/test/lib/xTestException.php","_root":{"kind":4096,"name":"file:///var/www/html/designpattern1/coreconcept/vendor/mindplay/annotations/test/lib/xTestException.php","location":{"uriHash":1622730086,"range":{"start":{"line":0,"character":0},"end":{"line":12,"character":0}}},"children":[{"kind":512,"name":"mindplay\\test\\lib","location":{"uriHash":1622730086,"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":28}}}},{"kind":1,"name":"mindplay\\test\\lib\\xTestException","location":{"uriHash":1622730086,"range":{"start":{"line":7,"character":0},"end":{"line":11,"character":1}}},"children":[{"kind":1024,"name":"FAIL","location":{"uriHash":1622730086,"range":{"start":{"line":9,"character":10},"end":{"line":9,"character":18}}},"modifiers":33,"value":"0","scope":"mindplay\\test\\lib\\xTestException"},{"kind":1024,"name":"PHP_ERROR","location":{"uriHash":1622730086,"range":{"start":{"line":10,"character":10},"end":{"line":10,"character":23}}},"modifiers":33,"value":"1","scope":"mindplay\\test\\lib\\xTestException"}],"associated":[{"kind":1,"name":"Exception"}],"doc":{"description":"The xTest::fail() method throws and catches this exception, in order to\ninterrupt the execution of a failed test.","type":""},"modifiers":0}]},"_hash":1622730086}]]